#######################################################################
#                          ShyGUI                                     #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  shygui:
    aliases:
      - "gui"
      - "menu"