name: ShyGUI
version: 1.1.2
author: Shynixn
main: com.github.shynixn.shygui.ShyGUIPlugin
softdepend: [ PlaceholderAPI]
api-version: 1.13
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-folia-api:2.16.0
  - com.github.shynixn.mccoroutine:mccoroutine-folia-core:2.16.0
  - com.google.inject:guice:7.0.0
  - com.google.code.gson:gson:2.10.1
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.23
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3
  - org.openjdk.nashorn:nashorn-core:15.4
  - aopalliance:aopalliance:1.0
