package com.github.shynixn.shygui.enumeration

enum class GUIItemConditionType {
    NONE,
    STRING_EQUALS,
    STRING_NOT_EQUALS,
    STRING_EQUALS_IGNORE_CASE,
    STRING_NOT_EQUALS_IGNORE_CASE,
    STRING_CONTAINS,
    STRING_NOT_CONTAINS,
    STRING_NOT_CONTAINS_IGNORE_CASE,
    STRING_CONTAINS_IGNORE_CASE,
    NUMBER_GREATER_THAN,
    NUMBER_GREATER_THAN_OR_EQUAL,
    NUMBER_LESS_THAN,
    NUMBER_LESS_THAN_OR_EQUAL,
    JAVASCRIPT,
}
